//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W500Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("W500Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to which
        ///there
        ///their
        ///about
        ///would
        ///these
        ///other
        ///words
        ///could
        ///write
        ///first
        ///water
        ///after
        ///where
        ///right
        ///think
        ///three
        ///years
        ///place
        ///sound
        ///great
        ///again
        ///still
        ///every
        ///small
        ///found
        ///those
        ///never
        ///under
        ///might
        ///while
        ///house
        ///world
        ///below
        ///asked
        ///going
        ///large
        ///until
        ///along
        ///shall
        ///being
        ///often
        ///earth
        ///began
        ///since
        ///study
        ///night
        ///light
        ///above
        ///paper
        ///parts
        ///young
        ///story
        ///point
        ///times
        ///heard
        ///whole
        ///white
        ///given
        ///means
        ///music
        ///miles
        ///thing
        ///today
        ///later
        ///using
        ///money
        ///lines
        ///order
        ///group
        ///among
        ///learn
        ///known
        ///space
        ///table
        ///early
        ///trees
        ///short
        ///hands
        ///state
        ///black
        ///shown
        ///stood
        ///front
        ///voice
        ///ki [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sgb_words {
            get {
                return ResourceManager.GetString("sgb-words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///aa
        ///aaa
        ///aaron
        ///ab
        ///abandoned
        ///abc
        ///aberdeen
        ///abilities
        ///ability
        ///able
        ///aboriginal
        ///abortion
        ///about
        ///above
        ///abraham
        ///abroad
        ///abs
        ///absence
        ///absent
        ///absolute
        ///absolutely
        ///absorption
        ///abstract
        ///abstracts
        ///abu
        ///abuse
        ///ac
        ///academic
        ///academics
        ///academy
        ///acc
        ///accent
        ///accept
        ///acceptable
        ///acceptance
        ///accepted
        ///accepting
        ///accepts
        ///access
        ///accessed
        ///accessibility
        ///accessible
        ///accessing
        ///accessories
        ///accessory
        ///accident
        ///accidents
        ///accommodate
        ///accommodation
        ///accommodations
        ///accompanied
        ///accompanying
        ///accomplish
        ///accomplished
        ///accordance
        ///according
        ///accordingly
        ///account
        ///ac [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wordlist_10000 {
            get {
                return ResourceManager.GetString("wordlist_10000", resourceCulture);
            }
        }
    }
}
